apiVersion: apps/v1
kind: Deployment
metadata:
  name: web1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web1
  template:
    metadata:
      labels:
        app: web1
    spec:
      containers:
      - name: web1-container
        image: ruchiwarke/project:latest
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: web1
spec:
  selector:
    app: web1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort
